services:
  db:
    image: mysql:8.0
    restart: always
    container_name: lifetrack-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lifetrack
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Container Principal (Usuário + Frontend + Gateway)
  user-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lifetrack-user
    restart: always
    ports:
      - "${PORT}:${PORT}" # Exposta para você (3000)
    environment:
      APP_MODE: "GATEWAY"
      ADMIN_SERVICE_URL: "http://lifetrack-admin:3000" # Endereço interno do admin
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    depends_on:
      db:
        condition: service_healthy
      admin-app:
        condition: service_started

  # Container de Admin (Escondido, apenas API)
  admin-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lifetrack-admin
    restart: always
    # Sem 'ports' -> Acessível apenas internamente pelo user-app
    environment:
      APP_MODE: "ADMIN_SERVICE"
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: